##  This file is autogenerated by vtkCreateArrayDispatchArrayList.cmake.
##  Do not edit this file. Your changes will not be saved.

import
  vtkTypeList, vtkAOSDataArrayTemplate

type
  Arrays* = Result[Create[vtkAOSDataArrayTemplate[char],
                        vtkAOSDataArrayTemplate[cdouble],
                        vtkAOSDataArrayTemplate[cfloat],
                        vtkAOSDataArrayTemplate[cint],
                        vtkAOSDataArrayTemplate[clong],
                        vtkAOSDataArrayTemplate[clonglong],
                        vtkAOSDataArrayTemplate[cshort],
                        vtkAOSDataArrayTemplate[cchar],
                        vtkAOSDataArrayTemplate[cuchar],
                        vtkAOSDataArrayTemplate[cuint],
                        vtkAOSDataArrayTemplate[culong],
                        vtkAOSDataArrayTemplate[culonglong],
                        vtkAOSDataArrayTemplate[cushort],
                        vtkAOSDataArrayTemplate[vtkIdType]]]

##  end namespace vtkArrayDispatch
