when defined(VTKACCELERATORSVTKMFILTERS_STATIC_DEFINE):
else:
when not defined(VTKACCELERATORSVTKMFILTERS_DEPRECATED):
  discard
when not defined(VTKACCELERATORSVTKMFILTERS_DEPRECATED_EXPORT):
  const
    VTKACCELERATORSVTKMFILTERS_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKACCELERATORSVTKMFILTERS_DEPRECATED_NO_EXPORT):
  const
    VTKACCELERATORSVTKMFILTERS_DEPRECATED_NO_EXPORT* = __attribute__(
        (__deprecated__))
when 0: