when defined(VTKACCELERATORSVTKMCORE_STATIC_DEFINE):
else:
when not defined(VTKACCELERATORSVTKMCORE_DEPRECATED):
  discard
when not defined(VTKACCELERATORSVTKMCORE_DEPRECATED_EXPORT):
  const
    VTKACCELERATORSVTKMCORE_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKACCELERATORSVTKMCORE_DEPRECATED_NO_EXPORT):
  const
    VTKACCELERATORSVTKMCORE_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: