when defined(VTKACCELERATORSVTKMDATAMODEL_STATIC_DEFINE):
else:
when not defined(VTKACCELERATORSVTKMDATAMODEL_DEPRECATED):
  discard
when not defined(VTKACCELERATORSVTKMDATAMODEL_DEPRECATED_EXPORT):
  const
    VTKACCELERATORSVTKMDATAMODEL_DEPRECATED_EXPORT* = __attribute__(
        (__deprecated__))
when not defined(VTKACCELERATORSVTKMDATAMODEL_DEPRECATED_NO_EXPORT):
  const
    VTKACCELERATORSVTKMDATAMODEL_DEPRECATED_NO_EXPORT* = __attribute__(
        (__deprecated__))
when 0: