when defined(VTKCOMMONCOMPUTATIONALGEOMETRY_STATIC_DEFINE):
else:
when not defined(VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED):
  discard
when not defined(VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_EXPORT):
  const
    VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_EXPORT* = __attribute__(
        (__deprecated__))
when not defined(VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_NO_EXPORT):
  const
    VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_NO_EXPORT* = __attribute__(
        (__deprecated__))
when 0: