
#ifndef VTKDOMAINSPARALLELCHEMISTRY_EXPORT_H
#define VTKDOMAINSPARALLELCHEMISTRY_EXPORT_H

#ifdef VTKDOMAINSPARALLELCHEMISTRY_STATIC_DEFINE
#  define VTKDOMAINSPARALLELCHEMISTRY_EXPORT
#  define VTKDOMAINSPARALLELCHEMISTRY_NO_EXPORT
#else
#  ifndef VTKDOMAINSPARALLELCHEMISTRY_EXPORT
#    ifdef DomainsParallelChemistry_EXPORTS
        /* We are building this library */
#      define VTKDOMAINSPARALLELCHEMISTRY_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKDOMAINSPARALLELCHEMISTRY_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKDOMAINSPARALLELCHEMISTRY_NO_EXPORT
#    define VTKDOMAINSPARALLELCHEMISTRY_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED
#  define VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED_EXPORT
#  define VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED_EXPORT VTKDOMAINSPARALLELCHEMISTRY_EXPORT VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED
#endif

#ifndef VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED_NO_EXPORT
#  define VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED_NO_EXPORT VTKDOMAINSPARALLELCHEMISTRY_NO_EXPORT VTKDOMAINSPARALLELCHEMISTRY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKDOMAINSPARALLELCHEMISTRY_NO_DEPRECATED
#    define VTKDOMAINSPARALLELCHEMISTRY_NO_DEPRECATED
#  endif
#endif
/* AutoInit dependencies. */
#include "vtkDomainsChemistryModule.h"


/* AutoInit implementations. */
#ifdef vtkDomainsParallelChemistry_AUTOINIT_INCLUDE
#include vtkDomainsParallelChemistry_AUTOINIT_INCLUDE
#endif
#ifdef vtkDomainsParallelChemistry_AUTOINIT
#include "vtkAutoInit.h"
VTK_MODULE_AUTOINIT(vtkDomainsParallelChemistry)
#endif

#endif /* VTKDOMAINSPARALLELCHEMISTRY_EXPORT_H */
