when defined(VTKFILTERSPARALLELIMAGING_STATIC_DEFINE):
else:
when not defined(VTKFILTERSPARALLELIMAGING_DEPRECATED):
  discard
when not defined(VTKFILTERSPARALLELIMAGING_DEPRECATED_EXPORT):
  const
    VTKFILTERSPARALLELIMAGING_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKFILTERSPARALLELIMAGING_DEPRECATED_NO_EXPORT):
  const
    VTKFILTERSPARALLELIMAGING_DEPRECATED_NO_EXPORT* = __attribute__(
        (__deprecated__))
when 0: