when defined(VTKFILTERSSTATISTICS_STATIC_DEFINE):
else:
when not defined(VTKFILTERSSTATISTICS_DEPRECATED):
  discard
when not defined(VTKFILTERSSTATISTICS_DEPRECATED_EXPORT):
  const
    VTKFILTERSSTATISTICS_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKFILTERSSTATISTICS_DEPRECATED_NO_EXPORT):
  const
    VTKFILTERSSTATISTICS_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: