
#ifndef VTKFILTERSPARALLELFLOWPATHS_EXPORT_H
#define VTKFILTERSPARALLELFLOWPATHS_EXPORT_H

#ifdef VTKFILTERSPARALLELFLOWPATHS_STATIC_DEFINE
#  define VTKFILTERSPARALLELFLOWPATHS_EXPORT
#  define VTKFILTERSPARALLELFLOWPATHS_NO_EXPORT
#else
#  ifndef VTKFILTERSPARALLELFLOWPATHS_EXPORT
#    ifdef FiltersParallelFlowPaths_EXPORTS
        /* We are building this library */
#      define VTKFILTERSPARALLELFLOWPATHS_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKFILTERSPARALLELFLOWPATHS_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKFILTERSPARALLELFLOWPATHS_NO_EXPORT
#    define VTKFILTERSPARALLELFLOWPATHS_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKFILTERSPARALLELFLOWPATHS_DEPRECATED
#  define VTKFILTERSPARALLELFLOWPATHS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKFILTERSPARALLELFLOWPATHS_DEPRECATED_EXPORT
#  define VTKFILTERSPARALLELFLOWPATHS_DEPRECATED_EXPORT VTKFILTERSPARALLELFLOWPATHS_EXPORT VTKFILTERSPARALLELFLOWPATHS_DEPRECATED
#endif

#ifndef VTKFILTERSPARALLELFLOWPATHS_DEPRECATED_NO_EXPORT
#  define VTKFILTERSPARALLELFLOWPATHS_DEPRECATED_NO_EXPORT VTKFILTERSPARALLELFLOWPATHS_NO_EXPORT VTKFILTERSPARALLELFLOWPATHS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKFILTERSPARALLELFLOWPATHS_NO_DEPRECATED
#    define VTKFILTERSPARALLELFLOWPATHS_NO_DEPRECATED
#  endif
#endif
/* AutoInit dependencies. */
#include "vtkFiltersFlowPathsModule.h"


/* AutoInit implementations. */
#ifdef vtkFiltersParallelFlowPaths_AUTOINIT_INCLUDE
#include vtkFiltersParallelFlowPaths_AUTOINIT_INCLUDE
#endif
#ifdef vtkFiltersParallelFlowPaths_AUTOINIT
#include "vtkAutoInit.h"
VTK_MODULE_AUTOINIT(vtkFiltersParallelFlowPaths)
#endif

#endif /* VTKFILTERSPARALLELFLOWPATHS_EXPORT_H */
