when defined(VTKFILTERSEXTRACTION_STATIC_DEFINE):
else:
when not defined(VTKFILTERSEXTRACTION_DEPRECATED):
  discard
when not defined(VTKFILTERSEXTRACTION_DEPRECATED_EXPORT):
  const
    VTKFILTERSEXTRACTION_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKFILTERSEXTRACTION_DEPRECATED_NO_EXPORT):
  const
    VTKFILTERSEXTRACTION_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: