when defined(VTKGUISUPPORTQTQUICK_STATIC_DEFINE):
else:
when not defined(VTKGUISUPPORTQTQUICK_DEPRECATED):
  discard
when not defined(VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT):
  const
    VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT):
  const
    VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: