
#ifndef VTKGUISUPPORTQTQUICK_EXPORT_H
#define VTKGUISUPPORTQTQUICK_EXPORT_H

#ifdef VTKGUISUPPORTQTQUICK_STATIC_DEFINE
#  define VTKGUISUPPORTQTQUICK_EXPORT
#  define VTKGUISUPPORTQTQUICK_NO_EXPORT
#else
#  ifndef VTKGUISUPPORTQTQUICK_EXPORT
#    ifdef GUISupportQtQuick_EXPORTS
        /* We are building this library */
#      define VTKGUISUPPORTQTQUICK_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKGUISUPPORTQTQUICK_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKGUISUPPORTQTQUICK_NO_EXPORT
#    define VTKGUISUPPORTQTQUICK_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED
#  define VTKGUISUPPORTQTQUICK_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT
#  define VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT VTKGUISUPPORTQTQUICK_EXPORT VTKGUISUPPORTQTQUICK_DEPRECATED
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT
#  define VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT VTKGUISUPPORTQTQUICK_NO_EXPORT VTKGUISUPPORTQTQUICK_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKGUISUPPORTQTQUICK_NO_DEPRECATED
#    define VTKGUISUPPORTQTQUICK_NO_DEPRECATED
#  endif
#endif

#endif /* VTKGUISUPPORTQTQUICK_EXPORT_H */
