when defined(VTKINFOVISBOOSTGRAPHALGORITHMS_STATIC_DEFINE):
else:
when not defined(VTKINFOVISBOOSTGRAPHALGORITHMS_DEPRECATED):
  discard
when not defined(VTKINFOVISBOOSTGRAPHALGORITHMS_DEPRECATED_EXPORT):
  const
    VTKINFOVISBOOSTGRAPHALGORITHMS_DEPRECATED_EXPORT* = __attribute__(
        (__deprecated__))
when not defined(VTKINFOVISBOOSTGRAPHALGORITHMS_DEPRECATED_NO_EXPORT):
  const
    VTKINFOVISBOOSTGRAPHALGORITHMS_DEPRECATED_NO_EXPORT* = __attribute__(
        (__deprecated__))
when 0: