when defined(VTKIMAGINGMORPHOLOGICAL_STATIC_DEFINE):
else:
when not defined(VTKIMAGINGMORPHOLOGICAL_DEPRECATED):
  discard
when not defined(VTKIMAGINGMORPHOLOGICAL_DEPRECATED_EXPORT):
  const
    VTKIMAGINGMORPHOLOGICAL_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKIMAGINGMORPHOLOGICAL_DEPRECATED_NO_EXPORT):
  const
    VTKIMAGINGMORPHOLOGICAL_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: