when defined(VTKINTERACTIONWIDGETS_STATIC_DEFINE):
else:
when not defined(VTKINTERACTIONWIDGETS_DEPRECATED):
  discard
when not defined(VTKINTERACTIONWIDGETS_DEPRECATED_EXPORT):
  const
    VTKINTERACTIONWIDGETS_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKINTERACTIONWIDGETS_DEPRECATED_NO_EXPORT):
  const
    VTKINTERACTIONWIDGETS_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: