##  This file was generated by the Octave script pythagorean_quadruples.
##  It contains lists of pseudo-Pythagorean quadruples sorted by increasing
##  distance from the origin. A pseudo-Pythagorean quadruple is a set of 4
##  numbers A, B, C, R such that
##     A * A + B * B + C * C = R * R
##  with A, B, and C having integer values and R being real. (Real
##  Pythagorean quadruples force R to be an integer as well.) Note that
##  the values below are stored as R*R, A, B, C so that all are integers.
##

var vtkPythagoreanQuadruples* {.importcpp: "vtkPythagoreanQuadruples",
                              header: "vtkPythagoreanQuadruples.h".}: UncheckedArray[
    cint]

var vtkMaxPythagoreanQuadrupleId* {.importcpp: "vtkMaxPythagoreanQuadrupleId",
                                  header: "vtkPythagoreanQuadruples.h".}: cint

##  VTK-HeaderTest-Exclude: vtkPythagoreanQuadruples.h
