when defined(VTKRENDERINGPARALLEL_STATIC_DEFINE):
else:
when not defined(VTKRENDERINGPARALLEL_DEPRECATED):
  discard
when not defined(VTKRENDERINGPARALLEL_DEPRECATED_EXPORT):
  const
    VTKRENDERINGPARALLEL_DEPRECATED_EXPORT* = __attribute__((__deprecated__))
when not defined(VTKRENDERINGPARALLEL_DEPRECATED_NO_EXPORT):
  const
    VTKRENDERINGPARALLEL_DEPRECATED_NO_EXPORT* = __attribute__((__deprecated__))
when 0: