
#ifndef VTKRENDERINGFREETYPEFONTCONFIG_EXPORT_H
#define VTKRENDERINGFREETYPEFONTCONFIG_EXPORT_H

#ifdef VTKRENDERINGFREETYPEFONTCONFIG_STATIC_DEFINE
#  define VTKRENDERINGFREETYPEFONTCONFIG_EXPORT
#  define VTKRENDERINGFREETYPEFONTCONFIG_NO_EXPORT
#else
#  ifndef VTKRENDERINGFREETYPEFONTCONFIG_EXPORT
#    ifdef RenderingFreeTypeFontConfig_EXPORTS
        /* We are building this library */
#      define VTKRENDERINGFREETYPEFONTCONFIG_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKRENDERINGFREETYPEFONTCONFIG_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKRENDERINGFREETYPEFONTCONFIG_NO_EXPORT
#    define VTKRENDERINGFREETYPEFONTCONFIG_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED
#  define VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED_EXPORT
#  define VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED_EXPORT VTKRENDERINGFREETYPEFONTCONFIG_EXPORT VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED
#endif

#ifndef VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED_NO_EXPORT
#  define VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED_NO_EXPORT VTKRENDERINGFREETYPEFONTCONFIG_NO_EXPORT VTKRENDERINGFREETYPEFONTCONFIG_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKRENDERINGFREETYPEFONTCONFIG_NO_DEPRECATED
#    define VTKRENDERINGFREETYPEFONTCONFIG_NO_DEPRECATED
#  endif
#endif
/* AutoInit dependencies. */
#include "vtkRenderingFreeTypeModule.h"


/* AutoInit implementations. */
#ifdef vtkRenderingFreeTypeFontConfig_AUTOINIT_INCLUDE
#include vtkRenderingFreeTypeFontConfig_AUTOINIT_INCLUDE
#endif
#ifdef vtkRenderingFreeTypeFontConfig_AUTOINIT
#include "vtkAutoInit.h"
VTK_MODULE_AUTOINIT(vtkRenderingFreeTypeFontConfig)
#endif

#endif /* VTKRENDERINGFREETYPEFONTCONFIG_EXPORT_H */
