
#ifndef VTKUTILITIESBENCHMARKS_EXPORT_H
#define VTKUTILITIESBENCHMARKS_EXPORT_H

#ifdef VTKUTILITIESBENCHMARKS_STATIC_DEFINE
#  define VTKUTILITIESBENCHMARKS_EXPORT
#  define VTKUTILITIESBENCHMARKS_NO_EXPORT
#else
#  ifndef VTKUTILITIESBENCHMARKS_EXPORT
#    ifdef UtilitiesBenchmarks_EXPORTS
        /* We are building this library */
#      define VTKUTILITIESBENCHMARKS_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKUTILITIESBENCHMARKS_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKUTILITIESBENCHMARKS_NO_EXPORT
#    define VTKUTILITIESBENCHMARKS_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKUTILITIESBENCHMARKS_DEPRECATED
#  define VTKUTILITIESBENCHMARKS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKUTILITIESBENCHMARKS_DEPRECATED_EXPORT
#  define VTKUTILITIESBENCHMARKS_DEPRECATED_EXPORT VTKUTILITIESBENCHMARKS_EXPORT VTKUTILITIESBENCHMARKS_DEPRECATED
#endif

#ifndef VTKUTILITIESBENCHMARKS_DEPRECATED_NO_EXPORT
#  define VTKUTILITIESBENCHMARKS_DEPRECATED_NO_EXPORT VTKUTILITIESBENCHMARKS_NO_EXPORT VTKUTILITIESBENCHMARKS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKUTILITIESBENCHMARKS_NO_DEPRECATED
#    define VTKUTILITIESBENCHMARKS_NO_DEPRECATED
#  endif
#endif

#endif /* VTKUTILITIESBENCHMARKS_EXPORT_H */
